### ISSUE TITLE
what is db-conn-string 'DRIVER'

### ISSUE THREAD

**Issue by xiaowu-ai-crypto** [woodlee/sqlserver-cdc-to-kafka#6]
l hava a problem in run python Locally. your means '--db-conn-string is  ODBC connection string for the DB from which you wish to consume CDC logs' .   so my windows mssql2017 ,l had install 
![image](https://user-images.githubusercontent.com/11933640/70788682-5e3fe100-1dcc-11ea-874e-f99dd92c60d7.png)  Microsoft ODBC Driver for SQL Server ..
but still error pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server ' : file not found (0) (SQLDriverConnect)")..
l do not kown what that happen .so l want your help  thank you .my email is  
  zhoutao9006@163.com

**Comment by woodlee** [comment]
@sharezhou what OS are you trying to run this on? If not Windows, did you follow the ODBC driver install instructions from https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15 ?
